services:
  ecorally-db:
    image: postgres:14
    container_name: ecorally-db
    restart: always
    ports:
      - 3080:5432
    env_file:
      - .env
    volumes:
      - ecorally-db:/var/lib/postgresql/data
  
  ecorally-redis:
    image: redis:7
    container_name: ecorally-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ecorally-redis:/data

volumes:
  ecorally-db:
    name: ecorally-docker-db
  ecorally-redis:
    name: ecorally-docker-redis
